name: emergency_alert
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  dotted_border: ^3.1.0
  firebase_ai: ^3.6.1
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^1.0.0
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.1.0
  font_awesome_flutter: ^10.12.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.6.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.2
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  google_generative_ai: ^0.4.3 # Use the latest version # The official Gemini SDK

  fast_contacts: ^5.0.1
  contacts_service: ^0.6.3
  intl: ^0.19.0 # For DateFormat

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    # - .env.example
    # - .env.example
    - assets/images/
